[client]
languageSync=true
remoteHost=192.168.0.226

[core]
computerName=SER8
coreMode=2
lastVersion=1.26.0.391
port=24800
preventSleep=false
processMode=1
screenName=SER8

[daemon]
elevate=false

[gui]
autoHide=false
closeReminder=false
closeToTray=true
enableUpdateCheck=false
logExpanded=true
shownFirstConnectedMessage=true
shownServerFirstStartMessage=true
startCoreWithGui=true
symbolicTrayIcon=false

[internalConfig]
hotkeys\size=0
screens\1\name=
screens\10\name=
screens\11\name=
screens\12\name=
screens\13\fixArray\1\fix=false
screens\13\fixArray\2\fix=false
screens\13\fixArray\3\fix=false
screens\13\fixArray\4\fix=false
screens\13\fixArray\size=4
screens\13\modifierArray\1\modifier=0
screens\13\modifierArray\2\modifier=1
screens\13\modifierArray\3\modifier=2
screens\13\modifierArray\4\modifier=3
screens\13\modifierArray\5\modifier=4
screens\13\modifierArray\6\modifier=5
screens\13\modifierArray\7\modifier=-1
screens\13\modifierArray\size=7
screens\13\name=zenbook
screens\13\switchCornerArray\1\switchCorner=false
screens\13\switchCornerArray\2\switchCorner=false
screens\13\switchCornerArray\3\switchCorner=false
screens\13\switchCornerArray\4\switchCorner=false
screens\13\switchCornerArray\size=4
screens\13\switchCornerSize=0
screens\14\name=
screens\15\name=
screens\2\name=
screens\3\name=
screens\4\name=
screens\5\name=
screens\6\name=
screens\7\name=
screens\8\fixArray\1\fix=false
screens\8\fixArray\2\fix=false
screens\8\fixArray\3\fix=false
screens\8\fixArray\4\fix=false
screens\8\fixArray\size=4
screens\8\modifierArray\1\modifier=0
screens\8\modifierArray\2\modifier=1
screens\8\modifierArray\3\modifier=2
screens\8\modifierArray\4\modifier=3
screens\8\modifierArray\5\modifier=4
screens\8\modifierArray\6\modifier=5
screens\8\modifierArray\7\modifier=-1
screens\8\modifierArray\size=7
screens\8\name=SER8
screens\8\switchCornerArray\1\switchCorner=false
screens\8\switchCornerArray\2\switchCorner=false
screens\8\switchCornerArray\3\switchCorner=false
screens\8\switchCornerArray\4\switchCorner=false
screens\8\switchCornerArray\size=4
screens\8\switchCornerSize=0
screens\9\name=
screens\size=15

[log]
file=/home/torridfish/deskflow.log
level=Info
toFile=false

[security]
certificate=/home/torridfish/.config/Deskflow/tls/deskflow.pem
checkPeerFingerprints=true
keySize=2048
tlsEnabled=true

[server]
clipboardSize=3
defaultLockToComputerState=false
disableLockToComputer=false
enableClipboard=true
enableHeatbeat=false
enableSwitchDelay=false
enableSwitchDoubleTap=false
externalConfig=true
externalConfigFile=/home/torridfish/.config/Deskflow/deskflow-server.conf
gridHeight=3
gridWidth=5
heartbeat=5000
protocol=barrier
relativeMouseMoves=false
switchDelay=250
switchDoubleTap=250
win32KeepForeground=false
