# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[✎](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
show_always = true      # 設為 true，即使在本地端也會顯示
style_user = "bold blue" # 設定一般使用者的顏色
style_root = "bold red" # 設定 root 使用者的顏色
format = "[$user]($style) " # 顯示格式

[hostname]
ssh_only = false        # 設為 false，在本地端也會顯示
style = "bold green"    # 設定主機名的顏色
format = "[$hostname]($style) " # 顯示格式
